### ISSUE TITLE
How to use trireme in a servlet container

### ISSUE THREAD

**Issue by sunchey11** [apigee/trireme#106]
I write a servlet using following code:

private NodeEnvironment env = new NodeEnvironment();
protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException {

		String script = request.getParameter("script");
		NodeScript script = env.createScript("hellotest", script, new String[0]);
		ScriptStatus status = script.execute().get();
}
It works fine. But spend a lot of time.
How can I use trireme in this situation.

**Comment by gbrail** [comment]
That works but it's a very inefficient way to do it, because you're running
the whole script every time.

Trireme has an "HTTP adapter" which is designed to allow it to plug in to
an existing container. There is a sample adapter (built using Netty) in the
"net" module. That would make your integration much more efficient.

However, it's not necessarily straightforward to build one of these. I have
been meaning for a long time to write a servlet example -- now may be a
good time.

Can I ask which servlet engine you are targeting? I'm wondering whether or
not the adapter could use async servlets or if it'd have to use the really
old stuff.

On Fri, Feb 27, 2015 at 1:23 AM, sunchey11 <notifications@github.com> wrote:

> I write a servlet using following code:
>
> private NodeEnvironment env = new NodeEnvironment();
> protected void doGet(HttpServletRequest request,
> HttpServletResponse response) throws ServletException {
>
>     String script = request.getParameter("script");
>     NodeScript script = env.createScript("hellotest", script, new String[0]);
>     ScriptStatus status = script.execute().get();
>
> }
> It works fine. But spend a lot of time.
> How can I use trireme in this situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/106>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by sunchey11** [comment]
Thank you very much.
We are using tomcat 6 or jetty 8.

**Comment by gbrail** [comment]
OK! I had been wanting to do that for a while so thanks for asking for it.

There's a new module called "trireme-servlet" that produces a servlet:

https://github.com/apigee/trireme/tree/master/servlet

and a sample under "samples/war" that shows how to use it.

It should be able to run any Node.js app that creates an HTTP server and which runs on Trireme presently.

**Comment by sunchey11** [comment]
It works fine.
Thank you very much.

**Comment by sunchey11** [comment]
I found out that the script in function handleRequest(in WEB-INF/node/server.js) run in one thread.
But our script code will call our old java program,which is not async mode and may be spend a lot of time.
When a lot of user requests come, handleRequest function will run it one by one.
Is it possible to run the servlet in multi thread mode?

**Comment by gbrail** [comment]
Can you explain the problem a bit more?

Are you calling in to Java code from inside your Node app, by registering a
Node module built in Java like in some of the Trireme examples?

https://github.com/apigee/trireme/tree/master/samples/java-stream

If that's what you're doing, then in lots of places in Trireme, we run in
to this problem as well. So when that happens, the Java code that is called
by Node uses a thread pool and dispatches the blocking Java work there.
Then, when the work in the thread pool is done, it dispatches work back to
the main Node thread where it can deliver a callback.

For instance, the example above is a Java module that appears as a Node
module with a callback, but what it actually does is use a Java thread pool
for all the blocking I/O. The "write" method in this class, for instance:

https://github.com/apigee/trireme/blob/master/samples/java-stream/src/main/java/io/apigee/trireme/samples/stream/WriteStream.java

Does exactly that -- when the JS code calls "write," it uses a thread pool
to write to the file from Java, and then when done it calls "enqueueTask"
to call the JavaScript callback back in the main script thread when it's
done.

Hope that makes sense and solves your problem -- otherwise, send some code
that we can look at and we'll see what we can do.


On Sat, Mar 7, 2015 at 2:48 AM, sunchey11 <notifications@github.com> wrote:

> I found out that the script in function handleRequest(in
> WEB-INF/node/server.js) run in one thread.
> But our script code will call our old java program,which is not async mode
> and may be spend a lot of time.
> When a lot of user requests come, handleRequest function will run it one
> by one.
> Is it possible to run the servlet in multi thread mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/106#issuecomment-77683813>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by sunchey11** [comment]
I know what you mean.
In my java module, the code

    ProcessInstance instance = startWorkflowProcess(...);
    
    will change to 
    
    self.runtime.getAsyncPool().execute(new Runnable() {
         @Override
         public void run()
         {
             ProcessInstance instance = startWorkflowProcess(...);
             deliverResult(instance, callbackFunction);
         }
    });
And that solves my problem. Thank you.
