### ISSUE TITLE
trireme-hello-sample

### ISSUE THREAD

**Issue by DavidApfel** [apigee/trireme#147]
When trying to run `java -jar trireme-hello-sample-0.8.9.jar` in samples/java-hello/target I get error: `no main manifest attribute, in trireme-hello-sample-0.8.9.jar`. It seems something is missing in the pom.xml and maven does not create the jar file correctly. Is there anything I can do to run the hello sample?

Thanks!

**Comment by gbrail** [comment]
That particular module isn't supposed to be a stand-alone application. It shows you how to write a module in Java that can be invoked from Trireme as if it were a regular Node module. The idea is that you would embed it in a larger app. For instance, you might use the sample code in the main readme to launch your app:

https://github.com/apigee/trireme#embedding-trireme-anywhere-else-that-java-runs

The only project that is a full-fledged app that runs in "java -jar" is the "jar" project. That module generates a file called "trireme-x.x.x.jar" that can be launched using "java -jar" because it has a "main".

**Comment by DavidApfel** [comment]
Thanks @gbrail . One more question: can I do the reverse: invoke a specific Node/Trireme module from Java and is there any sample code?

**Comment by gbrail** [comment]
Well that's a bit more complex and depends on what you want to do.

If you just want to launch a Node app from inside Java, then wait for it to
complete and get the result, then that's pretty easy -- the top-level
README file shows some sample code for that. You start the script, then
Trireme returns a Future so that you can wait for it right away, or check
later.

If you want to do something more complex, then it depends on what you want
to do.

In order to support all the things that Node does, when you start a script
in Trireme it starts a new thread, and the script runs there. As long as
you do something to keep the script running, like listen for requests, or
set a timer, or connect to a socket, it'll stay running there forever
(regular node works just the same way).

So if you want to call functions in your script from Java code, then it's a
little bit more complicated because you have to send the Trireme thread a
message saying to call a particular function. You do this using the
"NodeRuntime" interface, which you get from the "ScriptFuture" that's
returned when you start the script.

Of course, everything in Node is asynchronous, so you can ask Trireme to
call a function, but if you want to get the result then you probably want
to create a new Java-based module so that Trireme can notify you.

An example that does this is the "hadoop" sample, which runs functions
inside Hadoop. Or if you have more ideas of what you need then we can
suggest better samples.

On Wed, Feb 17, 2016 at 7:16 AM, DavidApfel <notifications@github.com>
wrote:

> Thanks @gbrail <https://github.com/gbrail> . One more question: can I do
> the reverse: invoke a specific Node/Trireme module from Java and is there
> any sample code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/147#issuecomment-185247514>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by DavidApfel** [comment]
Ok, I'll figure this out. Thanks a lot!
