### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by sathishceg** [apigee/trireme#148]
Will trireme support node version 5.* ???? If not till which node version it is compatible?

**Comment by sathishceg** [comment]
@gbrail can u help me with this question? Need to know till which node version trireme supports???

**Comment by gbrail** [comment]
Trireme currently supports Node 0.10.32 with mostly-complete support for
0.12.7.

Supporting new Node versions requires a lot of work on Rhino to support
more ES6 features, and then we can port code from newer Node versions. This
work is going very slowly because I have very little time to work on it and
no one else is contributing to Trireme right now. So, there's no specific
date for supporting newer Node versions.

On Fri, Mar 18, 2016 at 2:39 AM, SathishBabu <notifications@github.com>
wrote:

> @gbrail <https://github.com/gbrail> can u help me with this question?
> Need to know till which node version trireme supports???
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/148#issuecomment-198278612>
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
