### ISSUE TITLE
Stacktraces don't include the column number like node stacktraces do

### ISSUE THREAD

**Issue by kjg** [apigee/trireme#153]
For Example, on node: 

```
error: Unhandled Exception:
    at process._tickDomainCallback (node.js:463:13)
```

on trireme:

```
error: Unhandled Exception:
    at process._tickDomainCallback (node.js:463)
```

This makes [node-stack-trace](https://github.com/felixge/node-stack-trace) not parse these stack traces correctly due to [assuming the column number will always be present](https://github.com/felixge/node-stack-trace/blob/4a282316db4a2a93bdc91c6bc06c085ba878d5af/lib/stack-trace.js#L42)

**Comment by gbrail** [comment]
This is one of those things that we'd have to tackle in Rhino and not in
Trireme. Rhino stack traces don't have column numbers in them. However, I
could see enhancing Rhino so that every stack line has at least a column
number of zero in it so that parsing works the same.

At the same time, this is kind of a common problem of Trireme and Node,
namely:

   1. This is a pretty minor incompatibility, and Trireme will never ever
   be able to be even close to "100 percent" compatible with any particular
   version of Node.
   2. Lots and lots of Node code assumes that there is only a single
   JavaScript runtime where it can exist
   3. There is Node code out there that looks at the current stack trace
   (or at an exception) and decides what to do based on what it sees there. I
   was surprised to learn that, but it's out there.

**Comment by kjg** [comment]
If a new version of rhino is released with this change, is trireme in a place where it could use the newer rhino?

**Comment by gbrail** [comment]
Rhino doesn't know column numbers, but it now puts column "0" at the end of every stack trace so that it is more compatible with these kinds of tools.
