### ISSUE TITLE
Use Nashorn instead of Rhino (if available)

### ISSUE THREAD

**Issue by candrews** [apigee/trireme#50]
It would be great if Trireme could use Nashorn instead of Rhino if Nashorn is available. I think ideally, there should be a setting to specify the name of the engine to use, then if the engine isn't specified, Nashorn should be tried followed by Rhino.

Since Nashorn is faster and provides more javascript features than Rhino, it seems to be the clear choice (when there is one), and with Nashorn backports popping up, it may be a more realistic option soon even for users of Java < 8.

**Comment by gbrail** [comment]
This is a great thread that got a lot of interest. The "rowboat" project is an attempt to do this. It's a bit out of date and needs some TLS to get it finished, but a lot of modules work:

https://github.com/apigee/rowboat

Given how different Rhino and Nashorn are, I don't think it makes sense for Trireme to try and mode-switch in this way -- instead, rowboat is that project.

There is a "kernel" component of Trireme that Rowboat shares, so that it can take advantage of some of the work that we did on NIO and other things.

**Comment by mdedetrich** [comment]
@gbrail Is there any update on this (or maybe more precisely, the status of rowboat?)

**Comment by gbrail** [comment]
Honesty we made more progress this year making Rhino more compatible with
ES6 than we made on running Trireme on Rowboat. I also don't know the
status of ES6 features in Nashorn, but again it's been easier to make Rhino
more compatible, and there have been a few people working on other missing
ES6 features. So not much progress has been made on Rowboat.


On Tue, Dec 22, 2015 at 4:10 PM, Matthew de Detrich <
notifications@github.com> wrote:

> @gbrail <https://github.com/gbrail> Is there any update on this (or maybe
> more precisely, the status of rowboat?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/50#issuecomment-166766269>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by mdedetrich** [comment]
Thanks for the update, just wondering what the status of this is. Looks like rowboat will probably be a medium/long term proposition
